### PR TITLE
Issue 9 - Light Mode Feature

### LINKED ISSUE #9: [FEATURE REQUEST] Light mode

### PR DESCRIPTION
**Pull request by rjwignar**
This fixes #9 

Changes were tested by running Timeloom using `npm run dev` (`dev` script)

Summary of Changes
---
Modified the following files:

- `app/globals.css`
  - Added light mode styles
  - Modified base layer to apply light/dark mode styles to root based on user system preference
- `app/page.tsx`
  - Added landing page Header text gradient for light mode
  - Wrapped original text gradient styling in `dark:{class}` to apply them in dark mode
  - Added "Claim Username" blurb styling for light mode
  - Wrapped original blurb styling in `dark:{class}` to apply it in dark mode
- `components/Footer.tsx`
  - Added light mode styling for `Link` component in Footer
  - Wrapped original Link component styling inside `dark:{class}` to apply them in dark mode
- `components/ui/button.tsx`
  - Added hover coloring for light mode
  - Wrapped original hover coloring inside `dark:{class}` to apply them in dark mode
- `tailwind.config.ts`
  - extended dark mode settings to use `media` (for OS preference) strategy alongside existing `class` (manual) strategy, as per https://tailwindcss.com/docs/dark-mode
    - I noticed the order matters here
      - `darkMode: ["media", "class"],` enables **both** the `OS preference` strategy and `class` strategy
      - If `darkMode: ["class", "media"],` is used, **only** the `class` strategy is enabled

Prospective Changes (Pending Maintainer approval)
---
`bg-grid.png` for Light Mode
- If a Figma is provided, I will attempt to create a light mode version of `bg-grid.png` and add it to the assets.
- Logic will be used to show respective versions depending on light/dark mode.

### CODE REVIEW

**Comment by inclinedadarsh** [comment]
Heyy @rjwignar Let's skip the `bg-grid.png` for now, I'll open a new issue for that.

It seems like you're done working on this one, if so, please mark it for review.
Thanks!

**Comment by rjwignar** [comment]
I think I've marked it for review now.
Please let me know if it's the same on your end.

**Review by inclinedadarsh — CHANGES_REQUESTED** [review]
Heyy! It looks like the code needs a little bit of refactor. We have multiple times specified the same styles twice in `globals.css`

As we're using shadcn/ui for this project, have a look at their dark mode guide and let's use [Next Themes](https://www.npmjs.com/package/next-themes) to solve this issue.

**Comment by rjwignar** [comment]
I experimented with the Next Themes solution provided on a test branch and the solution only provides light/dark mode support similar to the media strategy used by [TailwindCSS](https://tailwindcss.com/docs/dark-mode).
I don't think the Next Themes strategy is required to refactor the code.

However, I can look into cleaning up `globals.css` so that styles are specified only once.

Alternatively, I can use the light/dark themes provided by Next Themes. However, this will likely **replace** the light/dark mode styles we created.

Please let me know which you would like me to do.

**Comment by rjwignar** [comment]
Yesterday I moved the `light` mode styles into the `root` styling and removed duplicate stylings from `globals.css`.
Please let me know if this refactor is sufficient, or if you would like to use one of `Next Themes`' light/dark mode presets instead.

**Review by inclinedadarsh — CHANGES_REQUESTED** [review]
Yep, it looks better now.

Can you do the following UI changes: 
1. Fix the header title color and make it darker.
image

2. The primary buttons don't look good. Please change it's text color to white and while hovering you can change the bg purple to something like a little light purple. No constraints, you can do whatever you think will be good.
image

3. This tags aren't visible in the dark mode. Add dark mode versions of them
image

4. This link text isn't visible. Make it a little darks, dark blue or something.
image


Everything else looks pretty good. Also, I have added the `hacktoberfest-accepted` label to this PR, so I believe it should show up in your hacktoberfest profile. You can take your time on this and proceed what whatever speed you want.

**Comment by rjwignar** [comment]
Thanks for the feedback!
I plan to work on this over the weekend.
I'll request another review when ready.

**Comment by rjwignar** [comment]
I've made the UI changes requested. Please let me know what you think!

**Review by inclinedadarsh — APPROVED** [review]
LGTM

**Pull request merged**
